language: generic

notifications:
  email: false

env:
  global:
    - CC=gcc-7
    - CXX=g++-7
    - PKG_NAME=cmlreaders
  matrix:
    - PYTHON_VERSION=3.5
    - PYTHON_VERSION=3.6

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda install -q python=$PYTHON_VERSION conda-build anaconda-client

install:
  - conda install -c pennmem -c conda-forge numpy pandas classiflib ptsa
  - pip install -r requirements.txt
  - conda build --python=$PYTHON_VERSION conda.recipe
  - ls $HOME/miniconda/conda-bld/linux-64
  - conda install --use-local $PKG_NAME

script:
  - flake8
  - python -m pytest -m "not rhino"

after_success:
  - codecov

deploy:
  - provider: script
    script: maint/deploy.sh
    on:
      tags: true
    skip_cleanup: true
